irc:
  channel: "#anthonykgross"
  port: 6667
  url: "irc.twitch.tv"
  login: "anthonykgross"
  pass: ""

config:
  nb_polls_to_summon: 5
  show_caution_at_percent: 50
  message_summon: "Pokemon go! %entity% attacks !"
  message_caution: "%entity% (%percent%%)"
  player_to_focus: "anthonykgross"